app.first_route:
    path: /my-first-route
    defaults:
        _controller: 'MakinaCorpus\Lannion\Controller\IndexController::myFirstRoute'
        _title: Ma première route
    requirements:
        _access: 'TRUE'

app.contenu_recent:
    path: /contenu-recent
    defaults:
        _controller: 'MakinaCorpus\Lannion\Controller\IndexController::contenuRecent'
        _title: Contenu récent
    requirements:
        _access: 'TRUE'
