services:

    # @todo use a compiler pass instead
    router.builder:
        class: MakinaCorpus\Lannion\Drupal\Routing\RouteBuilder
        arguments: ['@router.dumper', '@lock', '@event_dispatcher', '@module_handler', '@controller_resolver', '@access_manager.check_provider']
        lazy: true
        tags: [{ name: needs_destruction }]
